version: "3.7"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: gunicorn todo.config.wsgi -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
      - main

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - main
    volumes:
      - frontend_build:/var/www/frontend:ro

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - frontend_build:/frontend/dist

networks:
  main:

volumes:
  frontend_build:
